steps:
  # - id: trainer-docker
  #   name: gcr.io/cloud-builders/docker
  #   entrypoint: make
  #   args: ["image", "push"]

  - id: "migrate-db"
    name: "migrate/migrate:v4.14.1"
    secretEnv:
      - DATABASE_PASS
    entrypoint: /bin/sh
    args:
      - "-ce"
      - |
        apk add wget
        wget -q https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /usr/local/bin/cloud_sql_proxy
        chmod +x /usr/local/bin/cloud_sql_proxy
        cloud_sql_proxy -instances=${INSTANCE_CONNECTION_NAME}=tcp:5432 & sleep 2;
        migrate -database "postgres://${DATABASE_USER}:${DATABASE_PASS}@localhost:5432/${DATABASE_NAME}?sslmode=disable" \
          -path scripts/migrations/postgres up

options:
  dynamic_substitutions: true

substitutions:
  DATABASE_USER: postgres
  DATABASE_NAME: petsera
  INSTANCE_CONNECTION_NAME: ${PROJECT_ID}:europe-north1:petsera-postgres

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/petsera-db-password/versions/latest
      env: DATABASE_PASS
