apiVersion: v1
kind: Secret
metadata:
  metadata:
  name: {{ include "petsera.fullname" . }}
  labels:
    {{- include "petsera.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.config.db.password | b64enc }}
  mapsAPIKey: {{ .Values.config.mapsAPIKey | b64enc }}
